import mysql from 'mysql2/promise';
import dotenv from 'dotenv';
dotenv.config({ path: '/home/ubuntu/dinsmore-homestead/.env' });

const conn = await mysql.createConnection(process.env.DATABASE_URL);

const items = [
  ['childrens-lives-180-years-ago', 'lesson_plan', "Children's Lives 180 Years Ago", '1st-3rd Grade', "Designed for students in First through Third Grades, this program allows children to imagine what it might have been like growing up in the Nineteenth Century.\n\nActivities included:\n• Tour of the house focusing on artifacts & how they were used\n• Hands-on chores that children would have done in the past\n• Hands-on games, both indoor & outdoor, from the past\n• Learn about children's clothing of the past\n\nLearning Objectives:\n- Compare and contrast daily life in the 1840s with life today\n- Identify and describe artifacts from the 19th century\n- Understand how technology has changed daily life\n- Develop critical thinking skills through primary source analysis"],
  ['economy-antebellum-kentucky-agriculture', 'lesson_plan', 'The Economy of Antebellum Kentucky Agriculture', '4th-5th Grade', 'Students view an introductory video on Antebellum Kentucky Agriculture and create an organizer of the various groups that lived and worked on the Dinsmore farm. They study primary sources including Dinsmore family account books (1842-1865), Martha Dinsmore journal, tenant and day laborer account records, and enslaved peoples accounts.\n\nLearning Objectives:\n- Understand the economic structure of antebellum Kentucky agriculture\n- Analyze primary source documents including account books and journals\n- Compare the economic experiences of farm owners, tenants, day laborers, and enslaved people\n- Develop skills in historical thinking and source analysis\n\nKentucky Academic Standards: SS-05-2.1.1, SS-05-2.1.2, RI.5.1, RI.5.3, RI.5.6'],
  ['people-antebellum-kentucky-agriculture', 'lesson_plan', 'The People Involved in Antebellum Kentucky Agriculture', '4th-5th Grade', 'Students view an introductory video describing the various groups living and working on the Dinsmore farm and study the identities of various men, women, and children who actually lived and/or worked on the farm in the 1840s and 1850s.\n\nFarm Owners: James and Martha Dinsmore were the farm owners. James considered himself a scientific farmer.\n\nEnslaved People: The Dinsmore family enslaved between 12 and 16 people at various times.\n\nTenant Farmers: White tenant farmers lived on portions of the Dinsmore land.\n\nDay Laborers: Both white and free Black day laborers were hired for specific tasks.\n\nKentucky Academic Standards: SS-05-2.1.1, SS-05-4.1.1, RI.5.1, RI.5.6, RI.5.9'],
  ['school-group-programs', 'program', 'School & Group Programs', 'K-12', 'Bring history to life at the Dinsmore Farm! A visit to our indoor/outdoor museum will allow your students to experience how men, women, and children lived in the 19th and early 20th centuries.\n\nPrograms Available:\n- Childrens Lives 180 Years Ago (Grades 1-3)\n- Antebellum Kentucky Agriculture (Grades 4-5)\n- The Civil War and Its Aftermath (Grades 6-8)\n- The Progressive Era and Early 20th Century (Grades 9-12)\n\nPrograms run approximately 2 hours. Maximum group size: 30 students.\nContact: (859) 586-6117 or ccollopy@dinsmorehomestead.org'],
  ['scout-programs', 'program', 'Scout Programs', 'All Ages', 'Over the years Dinsmore has been grateful to have benefited from the Eagle Scout Program. Because our site is both indoors and outdoors, we offer a range of activities for Boy Scouts and Girl Scouts of all ages.\n\nBoy Scouts: American Cultures, American Heritage, Bird Study\nGirl Scouts: Outdoor Art Maker, Outdoor Art Apprentice, Playing the Past\n\nContact: (859) 586-6117 or ccollopy@dinsmorehomestead.org'],
  ['summer-programs', 'program', 'Pioneer-to-the-Past Summer Daycamp', 'Ages 6-12', 'Join us at the Dinsmore Homestead for an adventurous summer camp exploring great events from American History - no technology needed! Blaze a trail through the wilderness with Lewis and Clark, celebrate the 4th of July at a turn-of-the-century fair.\n\nCamp Activities:\n- Historical role-playing and living history demonstrations\n- Hands-on crafts and skills from the 19th century\n- Outdoor exploration of the 30-acre historic farm\n- Games and activities from the past\n\nSessions run 9:00 am to 1:00 pm. Contact (859) 586-6117 for registration.'],
  ['dinsmore-dispatch-newsletters', 'newsletter', 'Dinsmore Dispatch Newsletters', 'All', 'The Dinsmore Dispatch is the official newsletter of the Dinsmore Homestead Foundation. Published quarterly, it covers the latest news from the homestead, ongoing historical research, upcoming events, and preservation updates.\n\nAvailable Issues: Spring 2020, Summer 2020, Fall 2020, Winter 2020, Spring 2017, Nov-Dec 2016, Sept-Oct 2016'],
  ['primary-sources-letters-journals', 'research', 'Primary Sources: Dinsmore Family Letters & Journals', '6th Grade and Up', 'The Dinsmore family left behind an extraordinary collection of letters, journals, and poetry spanning more than a century.\n\nJulia Stockton Dinsmores Diaries: Julia kept detailed diaries for much of her adult life, recording daily farm operations, weather, family news, and observations on the wider world.\n\nThe Dinsmore-Flandrau Correspondence: Letters exchanged between the Dinsmore family and the Flandrau family in Minnesota.\n\nIsabella Selmes Ferguson Greenway King Papers: Correspondence with Theodore Roosevelt, Eleanor Roosevelt, and other prominent figures.\n\nAccount Books and Farm Records: Meticulous records of farm operations including accounts of enslaved people, tenant farmers, and day laborers.'],
];

for (const [slug, category, title, gradeLevel, content] of items) {
  await conn.execute(
    'INSERT INTO education_content (title, slug, category, gradeLevel, content, active, sortOrder, createdAt, updatedAt) VALUES (?, ?, ?, ?, ?, 1, 0, NOW(), NOW()) ON DUPLICATE KEY UPDATE title=VALUES(title), content=VALUES(content), updatedAt=NOW()',
    [title, slug, category, gradeLevel, content]
  );
  console.log('Seeded:', title);
}

await conn.end();
console.log('Done!');
