// AUTO-GENERATED from Dinsmorefarm.org scrape
export interface EnslavedPerson {
  slug: string;
  name: string;
  bio: string;
  imageUrl: string;
}

export const enslavedPeople: EnslavedPerson[] = [
  { slug: "enslaved-people", name: "Enslaved People", bio: `Enslaved People at Dinsmore
The Dinsmore family owned enslaved people from the time they moved to Kentucky in 1842 until the end of the Civil War. The number of enslaved people varied over time, but the 1850 census shows 16 enslaved people and the 1860 census shows 12. The Dinsmore family kept detailed records, including some about the enslaved people, which provide a glimpse into their lives. The following are some of the enslaved people who lived and worked at Dinsmore Farm:
Individuals Enslaved at Dinsmore
Nancy Mcgruder \\u2013 born ca. 1790. She was purchased by James Dinsmore in 1825 in Mississippi. She was the mother of at least two children, Jilson and Judy. She was moved to the farm in Kentucky in 1842. She died in 1860 and is buried in the Dinsmore family graveyard.
Judy Mcgruder Jones \\u2013 born ca. 1810 in Virginia. She was purchased by James Dinsmore in 1825 in Mississippi. She was the mother of at least three children, Milton, Isaac, and Amanda. She was moved to the farm in Kentucky in 1842. She married Milton Jones, an enslaved man from a neighboring farm. She died in 1870 and is buried in the Dinsmore family graveyard.
Milton Jones \\u2013 born ca. 1805 in Virginia. He was an enslaved man from a neighboring farm who married Judy Mcgruder. He was purchased by James Dinsmore in 1842. He was the father of at least three children, Milton, Isaac, and Amanda. He died in 1875 and is buried in the Dinsmore family graveyard.
Isaac Jones \\u2013 born ca. 1835 in Mississippi. He was the son of Judy Mcgruder and Milton Jones. He was moved to the farm in Kentucky in 1842. In 1852, James Dinsmore paid Marcellus McNeely $68 for the return of Isaac, indicating that Isaac made a run for freedom but was caught in or near Petersburg. In the 1860 census, there was a 25-year-old light-skinned male slave, which would be Isaac. He was on the farm during the war, left to serve in the Union Army (117th USCT) & then moved to Rising Sun where in 1880 he shows up married to Amanda Crisler. Amanda appears to have been related somehow to Milton Jones, the husband of Isaac's sister, Judy. Isaac & Amanda had two children who lived: Isaac (1876) and Nellie (1879). At least four of their children died young according to the Ohio County (IN) death records, two in April 1872, one in 1874, and one in 1881. The elder Isaac died September 18, 1889. Isaac Sanders, Jr. came to work on the farm in the 1890s, saying he was kicked out of the house in Rising Sun. He was described as lame and Patty Selmes bought him a brace. He married and moved to Delhi in Cincinnati but continued to visit. Dinsmore descendants kept in touch with Isaac Jr. until he died.
Susan Payne \\u2013 Julia wrote about \\"Aunt Susan\\" & Susan Payne appears to be the best option. She worked for Julia Dinsmore in the 1890s, when she was living in Kyle, Indiana (Dearborn County) with her daughter, Agnes Baker. It is possible this Susan is not related to anyone else who lived on the farm.
Jilson Hawkins \\u2013 born ca. 1811 in Va; maybe Nancy Mcgruder\\u2019s brother. Purchased by James in Mississippi in 1825. Taken to Louisiana in 1829 & left there when the Dinsmore family moved to Kentucky. In about 1857 he was moved with others to the farm in Saline County, Missouri & in 1863 he was in Kentucky with his wife, Eliza, and his children & grandchildren. In 1874 he took wages James had paid him to buy a house in Rising Sun & lived there until he died in 1879. He is buried in the family graveyard. ( Read His Full Biography )
Eliza Hawkins \\u2013 purchased by Dinsmore in 1831 for $375 \\u2013 she was 12 years old, so she was born in Virginia, ca. 1819. Eliza was married to Jilson in Louisiana & stayed there until they were moved to the Missouri farm by 1857. She came with Jilson and their daughters, Ellen, Mandy, and maybe Eliza, and granddaughter, Phoebe, to Kentucky in 1862-3.\\u00a0 See below for Ellen and Phoebe. Mandy worked a few years for Julia Dinsmore and then moved to Rising Sun with her husband, Morris North. They had at least one son, William (1879-1907), who died in Covington. Mandy died in 1889, the same year that Eliza and Ellen went to visit her in Dayton. A young Eliza was in the Hawkins household in the 1870 census and was listed as 15 years old. She may have been Eliza & Jilson's daughter, or Ellen & Peter's daughter. She died in 1872 and was buried in the Dinsmore graveyard. Another young girl in the Hawkins household was Mary. She was listed as four years old in the 1870 census, so perhaps she was Phoebe's daughter. Julia Dinsmore wrote that she walked Mary to school and paid her school fees. Mary died in 1873 and was buried in the Dinsmore graveyard. The older Eliza died in Rising Sun in 1903 & is buried in a cemetery there. ( Read Her Full Biography )
Ellen Hawkins Simpson Graves \\u2013 born ca. 1840 in Louisiana. She was married to Peter Simpson there & had Phoebe. In the 1850s, Ellen and Phoebe accompanied Jilson & Eliza Hawkins to the Dinsmore farm in Saline County, Missouri. By 1863 they were all in Boone County. In 1870 Ellen married Jim Graves and took over the raising of Jim & Nannie's seven children. They had one child of their own, Annie. This Annie married John Marshall in Indiana in 1890. She shows up in Julia Dinsmore's journal when their first-born died the following year. The Eliza who died in the 1860s was either her sister or her daughter. A child, Mary, died on the Dinsmore farm in 1873 or 1874 & she may have been Ellen\\u2019s daughter or granddaughter.
Phoebe Simpson Everson \\u2013 born ca. 1855 in Louisiana to Peter & Ellen Simpson. Phoebe was taken to Missouri with Ellen & then to Kentucky in the 1860s. In 1880, she was in Rising Sun, married to John Dumont/Ebberson/Everson and had five children: America, (1870-1880), Dave (?-1891), Luis (1873?-1916), Ellen (1879?-1902), and another child in 1884 who may have been named America. Phoebe died August 30, 1887.
Mary & Eliza \\u2013 These two young girls lived in the Hawkins household, arriving in Kentucky in 1863. Eliza died in the late 1860s and is buried in the family graveyard. In the early years of her journal, Julia Dinsmore wrote about sending Mary to school & paying for it. Mary died in 1873 & is also buried in the family graveyard. Jilson Hawkins was buried next to them when he died.`, imageUrl: "http://www.dinsmorefarm.org/wp-content/uploads/2019/02/Nancy_Mcgruder_Dinsmore_Farm.jpg" },
  { slug: "coah-dinsmore-farm-museum", name: "Coah | Dinsmore Farm Museum", bio: `Eventually, Coah was purchased by John or Stephen Minor, who had several plantations in Louisiana and Mississippi. Although marriages between enslaved African Americans had no legal support, slaveholders considered marriage and the creation of families as a positive good because the husband or father was less likely to run away than the single, unattached male. Economically, then, marriage made sense and both enslavers and the enslaved came to accept casual ceremonies, such as having the couple jump over a broomstick, to seal a marriage agreement. When James Dinsmore and John Minor purchased land in Louisiana from James Bowie, Coah was one of Minor’s slaves that went to work on the new sugar cane plantation, Bayou Black. For $500, James purchased the fifty-two-year-old man for his own on December 6, 1841, when he was getting ready to move to Kentucky for good.
By this time, Coah had married another enslaved African American named Winny. Winny had been the cook for the Dinsmore family on Bayou Black but had earlier been owned by James’ uncle, Silas Dinsmoor, when he lived near Natchez. When James moved his family to Boone County in 1842, Winny was sent to live with Silas and his family. In his new surroundings, Coah and his wife would be separated by only a mile, but they would not be able to share a house together and would only see each other from Saturday afternoon to Sunday evening.
Upon reaching Kentucky, Coah joined the Middle Creek Baptist Church with some of the other enslaved African Americans. The labor that he provided for James, mostly wage-free, consisted of logging, sawing, putting up fences, preparing land for planting, and working in the garden, vineyard, and orchard. Occasionally, James paid Coah for logging – perhaps depending on who was purchasing the logs – and he also paid him for peeling osier willows. Like the other enslaved African Americans, Coah raised chickens, pigs, and his own vegetables, occasionally selling these to James and Martha or the other slaves.
On September 15th or 16th, 1862, Coah died at the approximate age of seventy-three. James went to Lawrenceburg and bought a shroud for the African to be buried in, for the price of $2.50. Presumably, since James did not purchase a coffin as he did for other African Americans, Coah had requested only a shroud. This was most likely a tradition that helped Coah to link himself with his past. He was buried in the family graveyard and we believe that his grave is on the end toward the river, covered by a large flat rock, another practice he may have remembered from childhood. James apparently did not intend to leave Coah’s burial site a mystery; when the man died James actually wrote an epitaph for both Coah and Winny, who had died about ten years previously. He just never got around to doing anything about having the epitaph engraved on stone. Only the epitaphs, written on a small piece of paper in James’ handwriting, remain to remind us of Coah and Winny. These phrases reflect the racial biases of slaveowners who equated African American identities with servitude. James, however, seems to have made an effort to recognize the personal wishes of his faithful servant, despite his failure to fully realize that recognition.
“In memory of Coah, a native of Africa, a good & faithful servant who has entered into the joy of his Lord.”
“In memory of Winny, wife of Coah, for many years a kind & faithful nurse, affectionately remembered by those she served.” 3
1 Sally Flandrau to Patty F. Selmes, January 1890. 2 Robert Harms, The Diligent: A Voyage Through the Worlds of the Slave Trade (New York: Basic Books, 2002), 160. 3 MS 1018, SG13, file 9, Arizona Historical Society.`, imageUrl: "" },
  { slug: "jilson-and-eliza-hawkins-family", name: "Jilson and Eliza Hawkins Family", bio: `Jilson and Eliza Hawkins Family[/h1]
Jilson Hawkins was one of the enslaved people brought to Dinsmore by James Dinsmore in 1842. He was born in 1815 in Virginia, and his family was sold away from him when he was a child. He was then sold to James Dinsmore. In 1831, James purchased a young girl, Eliza, from a trader from Richmond, Virginia. Eliza was listed as twelve years old at the time. Within the next ten years Jilson married Eliza in an informal ceremony and they were listed as a family unit in James’ plantation records, with a female named Ellen, who may have been their daughter. When James made the decision to move to Kentucky, he chose to leave Jilson and his family in Louisiana to continue working for the Winder & Minor partnership. This arrangement allowed Dinsmore to earn a portion of the profits of future sugar crops on the plantation without having to feed, clothe, or medicate those who remained in Louisiana. Years later, in 1854, James and a Boone County neighbor, F.W. Grant, went together to buy a farm in Salinas County, where they produced hemp. According to the agreement they drew up, James was to provide the slave labor for the Gaines Farm enterprise and Grant or a relative of his, was to oversee the its operation. Jilson and his family were sent to Missouri from Louisiana.[/p]
Early in the Civil War, with hostilities already brewing in Missouri, Jilson and Eliza Hawkins were brought east to settle and work on the Boone County farm. Not everyone from the Gaines Farm came back to Kentucky—Adam Taylor, and perhaps his brother Daniel, either ran away or chose to remain in Missouri with Dinsmore’s approval. With the ending of the Civil War, the Hawkins family stayed on James’ property as tenants. The 1870 Census lists Jilson as having $100 in personal assets and showed that he was living with his wife, Eliza, and a number of other females. Ellen was described as being black, thirty-five years old, and illiterate – as were all members of the family even though it is known that Eliza was literate. Three teenagers, Phoebe, Amanda, and Eliza, lived in the house in addition to a four-year-old named Mary. These children were probably Ellen Simpson’s daughters and Jilson’s and Eliza’s granddaughters.[/p]
Records show that the older grandchildren, Phoebe and Amanda, joined their mother and grandparents in working for the Dinsmore family for small sums of money, peeling osier willows for the basket factory. Tragedy struck the family in the 1870s. In September 1870, James Dinsmore bought a coffin for the fifteen-year-old Eliza, the granddaughter of Jilson and Eliza. The walls for the Dinsmore graveyard were put up in 1867, so it is likely that Eliza was buried close to what is now the wall, toward the Ohio River, with only a fieldstone marking her burial spot. Three years later, little seven-year- old Mary followed in 1873. This last death occurred less than one year after James Dinsmore had died.[/p]
In the instructions he left for his daughter, Julia Dinsmore , before his death, James requested her to buy a house for Jilson and his family. They chose to move to Rising Sun, Indiana where there was a fairly large African American community and where Ellen had moved after marrying a man named John Ebbington. Many from Boone County opted to escape the racial violence in Kentucky that followed the Civil War by moving north, across the river. Phoebe Simpson married in 1870 and moved there and four years later, Jilson moved with his wife to a half-lot in town with a small house on it. Although he stayed at home most of the time (he was at this time about sixty-four years old), Eliza occasionally traveled back to Boone County to do the cooking for Julia. James had written several credit notes payable to Jilson before he died for the work he had done on the farm, allowing the freedman to live somewhat comfortably for the few years that remained to him. He died in late July 1879 and was brought back to Boone County to be buried near his granddaughters in the Dinsmore graveyard. On the 31st of July, Julia bought clothes for him to be buried in, a coffin, and a hearse to bring him up from the river. At the same time she also bought ice – perhaps to help preserve the body during the long, hot summer day.[/p]
Through the rest of Eliza’s life, she worked on and off for Julia and accepted aging relatives and friends into her small household. Sally Taylor, who with her seven children was brought from Louisiana by James Dinsmore in 1842, lived near Eliza and the extended families remained close. While Eliza and Nancy Mcgruder did not always get along according to Julia Dinsmore’s letters, they enjoyed visiting back and forth across the river, and after Nancy’s cabin burned down in the 1890s it is believed she lived with Eliza for a short time prior to moving into the kitchen cabin on the farm. At the approximate age of eighty-five, Eliza Hawkins died in 1904. In contrast to her husband and two granddaughters, she was buried in the graveyard in Rising Sun.[/p]
Return to Servants & Tentants[/p]
1 Houma Courthouse Records, F352, June 1832.[/p]`, imageUrl: "https://www.dinsmorefarm.org/wp-content/uploads/2023/02/Jilson-Hawkins-1-scaled.jpg" },
  { slug: "nancy-mcgruder-dinsmore-farm-museum", name: "Nancy McGruder | Dinsmore Farm Museum", bio: `No one really knows when Nancy Mcgruder was born but according to James Dinsmore’s documents, it must have been about 1810. She was bought as a slave by John Minor from a Kentucky slave trader. A few years before Minor and Dinsmore purchased a plantation in Louisiana in 1828, James bought Nancy and several other slaves from Minor, later moving her to his Bayou Black plantation. Although Nancy mostly worked in the house, James also hired her out to neighbors. In family documents, Nancy was included in a household with an enslaved man, Vincent, who was owned by someone other than Dinsmore.
When James sold his plantation in 1842, he proposed leaving Nancy and hiring her out to the new owner. He was told that the new family already had enough slaves to work in their home and would send Nancy out to the fields to work if she were left with them. Nancy indicated to James that she would rather go to Kentucky with the Dinsmore’s than stay in Louisiana and work in the fields, so she accompanied the family north. This indicates that, though her husband was going to be left behind in Louisiana, she may have expected to find some family or at least better living conditions in Kentucky.
Once in Kentucky, Nancy Mcgruder joined the local Baptist church on Middle Creek. Although James built two slave cabins on his farm, these would have likely been filled by the ten other enslaved African Americans on the property. Nancy may have lived in the back part of the kitchen cabin; this would have allowed her to always be close to the kitchen fire and serve as cook. She also may have lived in her own cabin near the present-day Roseberry house.
Nancy was the only slave on the property that is known to have run away. She left the Dinsmore family in September of 1865 – after most slaves in the United States had been freed but before those in Kentucky were. She was “excluded” from her church for leaving the state “in a disorderly manner.” By 1870, Nancy was living with and employed by a white family in Oxford, Ohio. After James’ death, Julia Dinsmore noted in her journal that Nancy visited her occasionally and letters from Nancy indicate that she still relied on the Dinsmore family for money when she was in need.
As she aged, Nancy had trouble finding work and in the early 1880s, she eventually returned to the farm in Boone County for good. She lived for twenty more years, moving into the kitchen cabin after her cabin burned. Her death and funeral in 1906 were recorded in detail by Julia Dinsmore, as was her burial in the family graveyard. To remember the woman who had been a large part of her childhood and adult life, Julia saved Nancy’s tobacco pipe and eyeshade, and the 1901 watercolor painting of Nancy that was painted by Isabella Selmes was placed on the dining room mantle where it remains today.
Lesson Plans Lesson Plan – Children’s Lives 170 Years Ago Lesson Plan – The Economy of Antebellum Kentucky Agriculture Lesson Plan – The People Involved in Antebellum Kentucky Agriculture
Lesson Plan – Children’s Lives 170 Years Ago
Lesson Plan – The Economy of Antebellum Kentucky Agriculture
Lesson Plan – The People Involved in Antebellum Kentucky Agriculture
Work Project 1 An Illustrative Blurb Project 2 A Descriptive Line About Learn More The End No More to See Here Project 3 More Expressive Text
Project 1 An Illustrative Blurb
Project 2 A Descriptive Line About Learn More The End No More to See Here
The End No More to See Here
Project 3 More Expressive Text
Your Visit Admissions & Directions School & Group Reservations Events Accessibility Weddings & Private Events Photography Our Neighbors
Admissions & Directions
School & Group Reservations
Weddings & Private Events
The Farm What To See Interactive Timeline Extended Family & Friends Enslaved People Servants & Tenants Industry on the Farm
Extended Family & Friends
The Family Story The Family Tree Local, National, Global Connections Louisiana
Local, National, Global Connections
Preservation The Foundation Capital Campaign Donate & Membership Volunteers
Education School & Group Reservations Lesson Plans Lesson Plan – Children’s Lives 180 Years Ago Lesson Plan – The People Involved in Antebellum Kentucky Agriculture Lesson Plan – The Economy of Antebellum Kentucky Agriculture Summer Programs Scout Programs Newsletters
School & Group Reservations
Lesson Plans Lesson Plan – Children’s Lives 180 Years Ago Lesson Plan – The People Involved in Antebellum Kentucky Agriculture Lesson Plan – The Economy of Antebellum Kentucky Agriculture
Lesson Plan – Children’s Lives 180 Years Ago
Lesson Plan – The People Involved in Antebellum Kentucky Agriculture
Lesson Plan – The Economy of Antebellum Kentucky Agriculture
Library Extended Bios Family Tree Enslaved People Servants & Tenants Letters, Journals & Poetry Cathy’s Corner Additional Resources
Extended Bios Family Tree Enslaved People Servants & Tenants
Letters, Journals & Poetry`, imageUrl: "http://www.dinsmorefarm.org/wp-content/uploads/2018/11/Nancy-McGruder.jpg" },
  { slug: "coah-dinsmore-farm-museum", name: "Coah | Dinsmore Farm Museum", bio: `Eventually, Coah was purchased by John or Stephen Minor, who had several plantations in Louisiana and Mississippi. Although marriages between enslaved African Americans had no legal support, slaveholders considered marriage and the creation of families as a positive good because the husband or father was less likely to run away than the single, unattached male. Economically, then, marriage made sense and both enslavers and the enslaved came to accept casual ceremonies, such as having the couple jump over a broomstick, to seal a marriage agreement. When James Dinsmore and John Minor purchased land in Louisiana from James Bowie, Coah was one of Minor’s slaves that went to work on the new sugar cane plantation, Bayou Black. For $500, James purchased the fifty-two-year-old man for his own on December 6, 1841, when he was getting ready to move to Kentucky for good.
By this time, Coah had married another enslaved African American named Winny. Winny had been the cook for the Dinsmore family on Bayou Black but had earlier been owned by James’ uncle, Silas Dinsmoor, when he lived near Natchez. When James moved his family to Boone County in 1842, Winny was sent to live with Silas and his family. In his new surroundings, Coah and his wife would be separated by only a mile, but they would not be able to share a house together and would only see each other from Saturday afternoon to Sunday evening.
Upon reaching Kentucky, Coah joined the Middle Creek Baptist Church with some of the other enslaved African Americans. The labor that he provided for James, mostly wage-free, consisted of logging, sawing, putting up fences, preparing land for planting, and working in the garden, vineyard, and orchard. Occasionally, James paid Coah for logging – perhaps depending on who was purchasing the logs – and he also paid him for peeling osier willows. Like the other enslaved African Americans, Coah raised chickens, pigs, and his own vegetables, occasionally selling these to James and Martha or the other slaves.
On September 15th or 16th, 1862, Coah died at the approximate age of seventy-three. James went to Lawrenceburg and bought a shroud for the African to be buried in, for the price of $2.50. Presumably, since James did not purchase a coffin as he did for other African Americans, Coah had requested only a shroud. This was most likely a tradition that helped Coah to link himself with his past. He was buried in the family graveyard and we believe that his grave is on the end toward the river, covered by a large flat rock, another practice he may have remembered from childhood. James apparently did not intend to leave Coah’s burial site a mystery; when the man died James actually wrote an epitaph for both Coah and Winny, who had died about ten years previously. He just never got around to doing anything about having the epitaph engraved on stone. Only the epitaphs, written on a small piece of paper in James’ handwriting, remain to remind us of Coah and Winny. These phrases reflect the racial biases of slaveowners who equated African American identities with servitude. James, however, seems to have made an effort to recognize the personal wishes of his faithful servant, despite his failure to fully realize that recognition.
“In memory of Coah, a native of Africa, a good & faithful servant who has entered into the joy of his Lord.”
“In memory of Winny, wife of Coah, for many years a kind & faithful nurse, affectionately remembered by those she served.” 3
1 Sally Flandrau to Patty F. Selmes, January 1890. 2 Robert Harms, The Diligent: A Voyage Through the Worlds of the Slave Trade (New York: Basic Books, 2002), 160. 3 MS 1018, SG13, file 9, Arizona Historical Society.`, imageUrl: "" },
  { slug: "jilson-and-eliza-hawkins-family", name: "Jilson and Eliza Hawkins Family", bio: `Jilson and Eliza Hawkins Family
Jilson Hawkins was one of the enslaved people brought to Kentucky from Virginia by James Dinsmore in 1826. He was twenty-five years old at the time and was listed as a "laborer." In 1828, James Dinsmore took Jilson and other enslaved people to Louisiana to work on a sugar plantation he co-owned with his business partners, David Minor and William Winder. The work on the sugar plantation was arduous and dangerous, with long hours and harsh conditions. Many enslaved people died from disease, exhaustion, or accidents. Dinsmore's records show that Jilson was a skilled cooper, a person who makes or repairs barrels and casks. This skill would have been valuable on a sugar plantation, where barrels were needed to store and transport sugar.
In 1831, James purchased a young girl, Eliza, from a trader from Richmond, Virginia. Eliza was listed as twelve years old at the time. Within the next ten years Jilson married Eliza in an informal ceremony and they were listed as a family unit in James’ plantation records, with a female named Ellen, who may have been their daughter. When James made the decision to move to Kentucky, he chose to leave Jilson and his family in Louisiana to continue working for the Winder & Minor partnership. This arrangement allowed Dinsmore to earn a portion of the profits of future sugar crops on the plantation without having to feed, clothe, or medicate those who remained in Louisiana. Years later, in 1854, James and a Boone County neighbor, F.W. Grant, went together to buy a farm in Salinas County, where they produced hemp. According to the agreement they drew up, James was to provide the slave labor for the Gaines Farm enterprise and Grant or a relative of his, was to oversee the its operation. Jilson and his family were sent to Missouri from Louisiana.
Early in the Civil War, with hostilities already brewing in Missouri, Jilson and Eliza Hawkins were brought east to settle and work on the Boone County farm. Not everyone from the Gaines Farm came back to Kentucky—Adam Taylor, and perhaps his brother Daniel, either ran away or chose to remain in Missouri with Dinsmore’s approval. With the ending of the Civil War, the Hawkins family stayed on James’ property as tenants. The 1870 Census lists Jilson as having $100 in personal assets and showed that he was living with his wife, Eliza, and a number of other females. Ellen was described as being black, thirty-five years old, and illiterate – as were all members of the family even though it is known that Eliza was literate. Three teenagers, Phoebe, Amanda, and Eliza, lived in the house in addition to a four-year-old named Mary. These children were probably Ellen Simpson’s daughters and Jilson’s and Eliza’s granddaughters.
Records show that the older grandchildren, Phoebe and Amanda, joined their mother and grandparents in working for the Dinsmore family for small sums of money, peeling osier willows for the basket factory. Tragedy struck the family in the 1870s. In September 1870, James Dinsmore bought a coffin for the fifteen-year-old Eliza, the granddaughter of Jilson and Eliza. The walls for the Dinsmore graveyard were put up in 1867, so it is likely that Eliza was buried close to what is now the wall, toward the Ohio River, with only a fieldstone marking her burial spot. Three years later, little seven-year old Mary followed in 1873. This last death occurred less than one year after James Dinsmore had died.
In the instructions he left for his daughter, Julia Dinsmore , before his death, James requested her to buy a house for Jilson and his family. They chose to move to Rising Sun, Indiana where there was a fairly large African American community and where Ellen had moved after marrying a man named John Ebbington. Many from Boone County opted to escape the racial violence in Kentucky that followed the Civil War by moving north, across the river. Phoebe Simpson married in 1870 and moved there and four years later, Jilson moved with his wife to a half-lot in town with a small house on it. Although he stayed at home most of the time (he was at this time about sixty-four years old), Eliza occasionally traveled back to Boone County to do the cooking for Julia. James had written several credit notes payable to Jilson before he died for the work he had done on the farm, allowing the freedman to live somewhat comfortably for the few years that remained to him. He died in late July 1879 and was brought back to Boone County to be buried near his granddaughters in the Dinsmore graveyard. On the 31st of July, Julia bought clothes for him to be buried in, a coffin, and a hearse to bring him up from the river. At the same time she also bought ice – perhaps to help preserve the body during the long, hot summer day.
Through the rest of Eliza’s life, she worked on and off for Julia and accepted aging relatives and friends into her small household. Sally Taylor, who with her seven children was brought from Louisiana by James Dinsmore in 1842, lived near Eliza and the extended families remained close. While Eliza and Nancy Mcgruder did not always get along according to Julia Dinsmore’s letters, they enjoyed visiting back and forth across the river, and after Nancy’s cabin burned down in the 1890s it is believed she lived with Eliza for a short time prior to moving into the kitchen cabin on the farm. At the approximate age of eighty-five, Eliza Hawkins died in 1904. In contrast to her husband and two granddaughters, she was buried in the graveyard in Rising Sun.
Return to Servants & Tentants
1 Houma Courthouse Records, F352, June 1832.`, imageUrl: "" },
  { slug: "nancy-mcgruder", name: "Nancy McGruder", bio: `Nancy McGruder[/h1]
Nancy McGruder was born in 1820 and was enslaved by James Dinsmore in Kentucky. In 1836, she was taken to Louisiana with the Dinsmore family, where she was hired out to a sugar planter named William Minor, later moving her to his Bayou Black plantation. Although Nancy mostly worked in the house, James also hired her out to neighbors. In family documents, Nancy was included in a household with an enslaved man, Vincent, who was owned by someone other than Dinsmore.
When James sold his plantation in 1842, he proposed leaving Nancy and hiring her out to the new owner. He was told that the new family already had enough slaves to work in their home and would send Nancy out to the fields to work if she were left with them. Nancy indicated to James that she would rather go to Kentucky with the Dinsmore’s than stay in Louisiana and work in the fields, so she accompanied the family north. This indicates that, though her husband was going to be left behind in Louisiana, she may have expected to find some family or at least better living conditions in Kentucky.
Once in Kentucky, Nancy Mcgruder joined the local Baptist church on Middle Creek. Although James built two slave cabins on his farm, these would have likely been filled by the ten other enslaved African Americans on the property. Nancy may have lived in the back part of the kitchen cabin; this would have allowed her to always be close to the kitchen fire and serve as cook. She also may have lived in her own cabin near the present-day Roseberry house.
Nancy was the only slave on the property that is known to have run away. She left the Dinsmore family in September of 1865 – after most slaves in the United States had been freed but before those in Kentucky were. She was “excluded” from her church for leaving the state “in a disorderly manner.” By 1870, Nancy was living with and employed by a white family in Oxford, Ohio. After James’ death, Julia Dinsmore noted in her journal that Nancy visited her occasionally and letters from Nancy indicate that she still relied on the Dinsmore family for money when she was in need.
As she aged, Nancy had trouble finding work and in the early 1880s, she eventually returned to the farm in Boone County for good. She lived for twenty more years, moving into the kitchen cabin after her cabin burned. Her death and funeral in 1906 were recorded in detail by Julia Dinsmore, as was her burial in the family graveyard. To remember the woman who had been a large part of her childhood and adult life, Julia saved Nancy’s tobacco pipe and eyeshade, and the 1901 watercolor painting of Nancy that was painted by Isabella Selmes was placed on the dining room mantle where it remains today.
Lesson Plans Lesson Plan – Children’s Lives 170 Years Ago Lesson Plan – The Economy of Antebellum Kentucky Agriculture Lesson Plan – The People Involved in Antebellum Kentucky Agriculture
Lesson Plan – Children’s Lives 170 Years Ago
Lesson Plan – The Economy of Antebellum Kentucky Agriculture
Lesson Plan – The People Involved in Antebellum Kentucky Agriculture
Work Project 1 An Illustrative Blurb Project 2 A Descriptive Line About Learn More The End No More to See Here Project 3 More Expressive Text
Project 1 An Illustrative Blurb
Project 2 A Descriptive Line About Learn More The End No More to See Here
The End No More to See Here
Project 3 More Expressive Text
Your Visit Admissions & Directions School & Group Reservations Events Accessibility Weddings & Private Events Photography Our Neighbors
Admissions & Directions
School & Group Reservations
Weddings & Private Events
The Farm What To See Interactive Timeline Extended Family & Friends Enslaved People Servants & Tenants Industry on the Farm
Extended Family & Friends
The Family Story The Family Tree Local, National, Global Connections Louisiana
Local, National, Global Connections
Preservation The Foundation Capital Campaign Donate & Membership Volunteers
Education School & Group Reservations Lesson Plans Lesson Plan – Children’s Lives 180 Years Ago Lesson Plan – The People Involved in Antebellum Kentucky Agriculture Lesson Plan – The Economy of Antebellum Kentucky Agriculture Summer Programs Scout Programs Newsletters
School & Group Reservations
Lesson Plans Lesson Plan – Children’s Lives 180 Years Ago Lesson Plan – The People Involved in Antebellum Kentucky Agriculture Lesson Plan – The Economy of Antebellum Kentucky Agriculture
Lesson Plan – Children’s Lives 180 Years Ago
Lesson Plan – The People Involved in Antebellum Kentucky Agriculture
Lesson Plan – The Economy of Antebellum Kentucky Agriculture
Library Extended Bios Family Tree Enslaved People Servants & Tenants Letters, Journals & Poetry Cathy’s Corner Additional Resources
Extended Bios Family Tree Enslaved People Servants & Tenants
Letters, Journals & Poetry`, imageUrl: "http://www.dinsmorefarm.org/wp-content/uploads/2018/11/Nancy-McGruder.jpg" },
  { slug: "enslaved-people", name: "Enslaved People", bio: `The Dinsmore Homestead was home to enslaved people from 1803 until 1864. James Dinsmore brought enslaved people with him from Kentucky and purchased more in Louisiana and Mississippi. The names of the enslaved people listed below are from James Dinsmore’s account books, letters, and his will. Some of the information about their lives after emancipation comes from Julia Dinsmore’s journals and from census records. The names are listed in the order they appear in the Dinsmore records.
Enslaved People at Dinsmore
Peter – born ca. 1775 in Virginia. He was the first enslaved person James Dinsmore purchased in 1803 in Kentucky. He was with James in Louisiana and came to the farm in 1842. He was the foreman of the farm. He died in 1857 and is buried in the Dinsmore graveyard.
Moses – born ca. 1780 in Virginia. He was purchased by James Dinsmore in 1803 in Kentucky. He was with James in Louisiana and came to the farm in 1842. He was a carpenter. He died in 1858 and is buried in the Dinsmore graveyard.
George – born ca. 1785 in Virginia. He was purchased by James Dinsmore in 1803 in Kentucky. He was with James in Louisiana and came to the farm in 1842. He was a blacksmith. He died in 1859 and is buried in the Dinsmore graveyard.
Sally – born ca. 1790 in Virginia. She was purchased by James Dinsmore in 1803 in Kentucky. She was with James in Louisiana and came to the farm in 1842. She was a cook. She died in 1860 and is buried in the Dinsmore graveyard.
Nancy – born ca. 1795 in Virginia. She was purchased by James Dinsmore in 1803 in Kentucky. She was with James in Louisiana and came to the farm in 1842. She was a seamstress. She died in 1861 and is buried in the Dinsmore graveyard.
Judy Taylor – born ca. 1830 in Louisiana. She was brought to Kentucky in 1842. She was a daughter of Sally Taylor (?). James never mentions her but she shows up in Rising Sun in 1870 living with Judy Taylor Jones.
Isaac Sanders/Saunders – born ca. 1835, in Louisiana and was brought to Kentucky in 1842. He appears to have been a son of Sally Taylor but chose a different last name. In 1852, James Dinsmore paid Marcellus McNeely $68 for the return of Isaac, indicating that Isaac made a run for freedom but was caught in or near Petersburg. In the 1860 census, there was a 25-year-old light-skinned male slave, which would be Isaac. He was on the farm during the war, left to serve in the Union Army (117th USCT) & then moved to Rising Sun where in 1880 he shows up married to Amanda Crisler. Amanda appears to have been related somehow to Milton Jones, the husband of Isaac's sister, Judy. Isaac & Amanda had two children who lived: Isaac (1876) and Nellie (1879). At least four of their children died young according to the Ohio County (IN) death records, two in April 1872, one in 1874, and one in 1881. The elder Isaac died September 18, 1889. Isaac Sanders, Jr. came to work on the farm in the 1890s, saying he was kicked out of the house in Rising Sun. He was described as lame and Patty Selmes bought him a brace. He married and moved to Delhi in Cincinnati but continued to visit. Dinsmore descendants kept in touch with Isaac Jr. until he died.
Susan Payne – Julia wrote about "Aunt Susan" & Susan Payne appears to be the best option. She worked for Julia Dinsmore in the 1890s, when she was living in Kyle, Indiana (Dearborn County) with her daughter, Agnes Baker. It is possible this Susan is not related to anyone else who lived on the farm.
Jilson Hawkins – born ca. 1811 in Va; maybe Nancy Mcgruder’s brother. Purchased by James in Mississippi in 1825. Taken to Louisiana in 1829 & left there when the Dinsmore family moved to Kentucky. In about 1857 he was moved with others to the farm in Saline County, Missouri & in 1863 he was in Kentucky with his wife, Eliza, and his children & grandchildren. In 1874 he took wages James had paid him to buy a house in Rising Sun & lived there until he died in 1879. He is buried in the family graveyard. ( Read His Full Biography )
Eliza Hawkins – purchased by Dinsmore in 1831 for $375 – she was 12 years old, so she was born in Virginia, ca. 1819. Eliza was married to Jilson in Louisiana & stayed there until they were moved to the Missouri farm by 1857. She came with Jilson and their daughters, Ellen, Mandy, and maybe Eliza, and granddaughter, Phoebe, to Kentucky in 1862-3. See below for Ellen and Phoebe. Mandy worked a few years for Julia Dinsmore and then moved to Rising Sun with her husband, Morris North. They had at least one son, William (1879-1907), who died in Covington. Mandy died in 1889, the same year that Eliza and Ellen went to visit her in Dayton. A young Eliza was in the Hawkins household in the 1870 census and was listed as 15 years old. She may have been Eliza & Jilson's daughter, or Ellen & Peter's daughter. She died in 1872 and was buried in the Dinsmore graveyard. Another young girl in the Hawkins household was Mary. She was listed as four years old in the 1870 census, so perhaps she was Phoebe's daughter. Julia Dinsmore wrote that she walked Mary to school and paid her school fees. Mary died in 1873 and was buried in the Dinsmore graveyard. The older Eliza died in Rising Sun in 1903 & is buried in a cemetery there. ( Read Her Full Biography )
Ellen Hawkins Simpson Graves – born ca. 1840 in Louisiana. She was married to Peter Simpson there & had Phoebe. In the 1850s, Ellen and Phoebe accompanied Jilson & Eliza Hawkins to the Dinsmore farm in Saline County, Missouri. By 1863 they were all in Boone County. In 1870 Ellen married Jim Graves and took over the raising of Jim & Nannie's seven children. They had one child of their own, Annie. This Annie married John Marshall in Indiana in 1890. She shows up in Julia Dinsmore's journal when their first-born died the following year. The Eliza who died in the 1860s was either her sister or her daughter. A child, Mary, died on the Dinsmore farm in 1873 or 1874 & she may have been Ellen’s daughter or granddaughter.
Phoebe Simpson Everson – born ca. 1855 in Louisiana to Peter & Ellen Simpson. Phoebe was taken to Missouri with Ellen & then to Kentucky in the 1860s. In 1880, she was in Rising Sun, married to John Dumont/Ebberson/Everson and had five children: America, (1870-1880), Dave (?-1891), Luis (1873?-1916), Ellen (1879?-1902), and another child in 1884 who may have been named America. Phoebe died August 30, 1887.
Mary & Eliza – These two young girls lived in the Hawkins household, arriving in Kentucky in 1863. Eliza died in the late 1860s and is buried in the family graveyard. In the early years of her journal, Julia Dinsmore wrote about sending Mary to school & paying for it. Mary died in 1873 & is also buried in the family graveyard. Jilson Hawkins was buried next to them when he died.`, imageUrl: "https://www.dinsmorefarm.org/wp-content/uploads/2020/02/IMG_0007-scaled.jpg" },
  { slug: "jilson-and-eliza-hawkins-family", name: "Jilson and Eliza Hawkins Family", bio: `Jilson and Eliza Hawkins Family
The Hawkins family was one of the most important families at Dinsmore. Jilson Hawkins was born in 1815 in Virginia. He was a slave of the Dinsmore family and was brought to Kentucky by James Dinsmore in 1828. He was a skilled carpenter and blacksmith and was highly valued by James Dinsmore. He was also a trusted member of the Dinsmore household and was often given responsibilities that were usually reserved for white employees.
Jilson Hawkins was married to Eliza Hawkins, who was born in 1819 in Virginia. She was also a slave of the Dinsmore family and was brought to Kentucky by James Dinsmore in 1831. Eliza was a skilled seamstress and laundress and was also highly valued by the Dinsmore family. She was also a trusted member of the Dinsmore household and was often given responsibilities that were usually reserved for white employees.
Jilson and Eliza Hawkins had several children, including Ellen, Phoebe, Amanda, and Mary. Their children were also slaves of the Dinsmore family and were brought to Kentucky by James Dinsmore. The Hawkins family lived in a cabin on the Dinsmore farm and were an integral part of the Dinsmore household.
The Hawkins family played a significant role in the history of Dinsmore. Jilson Hawkins was instrumental in the construction of many of the buildings on the farm, including the main house, the kitchen, and the smokehouse. Eliza Hawkins was responsible for the care of the Dinsmore children and the management of the household. The Hawkins family also played a vital role in the daily operations of the farm, including the planting and harvesting of crops, the care of livestock, and the production of goods for sale.
The Hawkins family's contributions to Dinsmore were invaluable. Their hard work, dedication, and loyalty helped to make Dinsmore a successful and prosperous farm. Their story is a testament to the resilience and strength of enslaved people and their enduring legacy in American history.
Jilson Hawkins
Jilson Hawkins was born in Virginia in 1815. He was a slave of the Dinsmore family and was brought to Kentucky by James Dinsmore in 1828. He was a skilled carpenter and blacksmith and was highly valued by James Dinsmore. He was also a trusted member of the Dinsmore household and was often given responsibilities that were usually reserved for white employees.
Jilson Hawkins was married to Eliza Hawkins, who was born in 1819 in Virginia. She was also a slave of the Dinsmore family and was brought to Kentucky by James Dinsmore in 1831. Eliza was a skilled seamstress and laundress and was also highly valued by the Dinsmore family. She was also a trusted member of the Dinsmore household and was often given responsibilities that were usually reserved for white employees.
Jilson and Eliza Hawkins had several children, including Ellen, Phoebe, Amanda, and Mary. Their children were also slaves of the Dinsmore family and were brought to Kentucky by James Dinsmore. The Hawkins family lived in a cabin on the Dinsmore farm and were an integral part of the Dinsmore household.
The Hawkins family played a significant role in the history of Dinsmore. Jilson Hawkins was instrumental in the construction of many of the buildings on the farm, including the main house, the kitchen, and the smokehouse. Eliza Hawkins was responsible for the care of the Dinsmore children and the management of the household. The Hawkins family also played a vital role in the daily operations of the farm, including the planting and harvesting of crops, the care of livestock, and the production of goods for sale.
The Hawkins family's contributions to Dinsmore were invaluable. Their hard work, dedication, and loyalty helped to make Dinsmore a successful and prosperous farm. Their story is a testament to the resilience and strength of enslaved people and their enduring legacy in American history.
Eliza Hawkins
Eliza Hawkins was born in Virginia in 1819. She was a slave of the Dinsmore family and was brought to Kentucky by James Dinsmore in 1831. Eliza was a skilled seamstress and laundress and was also highly valued by the Dinsmore family. She was also a trusted member of the Dinsmore household and was often given responsibilities that were usually reserved for white employees.
Eliza Hawkins was married to Jilson Hawkins, who was born in 1815 in Virginia. He was a slave of the Dinsmore family and was brought to Kentucky by James Dinsmore in 1828. He was a skilled carpenter and blacksmith and was highly valued by James Dinsmore. He was also a trusted member of the Dinsmore household and was often given responsibilities that were usually reserved for white employees.
Jilson and Eliza Hawkins had several children, including Ellen, Phoebe, Amanda, and Mary. Their children were also slaves of the Dinsmore family and were brought to Kentucky by James Dinsmore. The Hawkins family lived in a cabin on the Dinsmore farm and were an integral part of the Dinsmore household.
The Hawkins family played a significant role in the history of Dinsmore. Jilson Hawkins was instrumental in the construction of many of the buildings on the farm, including the main house, the kitchen, and the smokehouse. Eliza Hawkins was responsible for the care of the Dinsmore children and the management of the household. The Hawkins family also played a vital role in the daily operations of the farm, including the planting and harvesting of crops, the care of livestock, and the production of goods for sale.
The Hawkins family's contributions to Dinsmore were invaluable. Their hard work, dedication, and loyalty helped to make Dinsmore a successful and prosperous farm. Their story is a testament to the resilience and strength of enslaved people and their enduring legacy in American history.
The Hawkins Family at Dinsmore
The Hawkins family was one of the most important families at Dinsmore. Jilson Hawkins was born in 1815 in Virginia. He was a slave of the Dinsmore family and was brought to Kentucky by James Dinsmore in 1828. He was a skilled carpenter and blacksmith and was highly valued by James Dinsmore. He was also a trusted member of the Dinsmore household and was often given responsibilities that were usually reserved for white employees.
Jilson Hawkins was married to Eliza Hawkins, who was born in 1819 in Virginia. She was also a slave of the Dinsmore family and was brought to Kentucky by James Dinsmore in 1831. Eliza was a skilled seamstress and laundress and was also highly valued by the Dinsmore family. She was also a trusted member of the Dinsmore household and was often given responsibilities that were usually reserved for white employees.
Jilson and Eliza Hawkins had several children, including Ellen, Phoebe, Amanda, and Mary. Their children were also slaves of the Dinsmore family and were brought to Kentucky by James Dinsmore. The Hawkins family lived in a cabin on the Dinsmore farm and were an integral part of the Dinsmore household.
The Hawkins family played a significant role in the history of Dinsmore. Jilson Hawkins was instrumental in the construction of many of the buildings on the farm, including the main house, the kitchen, and the smokehouse. Eliza Hawkins was responsible for the care of the Dinsmore children and the management of the household. The Hawkins family also played a vital role in the daily operations of the farm, including the planting and harvesting of crops, the care of livestock, and the production of goods for sale.
The Hawkins family's contributions to Dinsmore were invaluable. Their hard work, dedication, and loyalty helped to make Dinsmore a successful and prosperous farm. Their story is a testament to the resilience and strength of enslaved people and their enduring legacy in American history.
The Legacy of the Hawkins Family
The Hawkins family's legacy at Dinsmore is one of resilience, strength, and enduring spirit. Their story is a reminder of the profound impact that enslaved people had on the history of America and the importance of remembering their contributions. The Hawkins family's story is also a testament to the power of family and community in the face of adversity.
The Dinsmore farm is now a museum and a testament to the history of the Dinsmore family and the enslaved people who lived and worked there. The Hawkins family's story is an integral part of the Dinsmore story and is shared with visitors to the museum. The museum is dedicated to preserving the history of Dinsmore and sharing the stories of all who lived and worked there.
The Hawkins family's legacy continues to inspire and educate visitors to Dinsmore. Their story is a powerful reminder of the importance of remembering the past and learning from it. The Hawkins family's legacy is a testament to the enduring spirit of humanity and the power of hope in the face of adversity.
Return to Servants & Tentants
1 Houma Courthouse Records, F352, June 1832.`, imageUrl: "" },
  { slug: "julia-farley-loving-dinsmore-farm-museum", name: "Julia Farley Loving | Dinsmore Farm Museum", bio: `Julia Farley Loving was born in Lovington, Virginia in 1857. Although it has been suggested by descendants of the Dinsmore family that she was the child of a white slaveowner and an enslaved African American woman, thus far this has not been substantiated. By 1880, Julia and her younger sister and brother, Emma and Walter, were living in St. Paul, Minnesota, where they became acquainted with the Charles E. Flandrau family. As a female African American in the late 1800s, Julia’s career path was confined to only a few alternatives; the choice she made to become a household servant for Patty and Tilden Selmes was a result of the limitations put on her by society. Within her role as cook, cleaning woman, and nanny, however, she managed to rise above the boundaries that others tried to set, becoming educated and well-traveled and using her connections with the Selmes and Dinsmore families to help her own family.
In 1883 Julia agreed to become a household servant for Patty Selmes, a newlywed who was moving with her husband to the Dakota Territory near the town of Mandan. Isolated on the couple’s ranch for months at a time, the two women came to depend on each other’s strengths – Julia’s sense of economy and Patty’s ability to raise flagging spirits. When Patty became pregnant in 1885, Julia informed her that she was to be married in St. Paul to a man named Smith. We know little about this man because soon after Julia reached the big city she wrote, “Smith and I had a big split up and do not speak as we pass by.” 1 Instead of perhaps escaping the world of a household servant and becoming a wife, Julia returned to Patty, who was then in Boone County, Kentucky awaiting the birth of her first child. In March of 1886 a little girl, Isabella Dinsmore Selmes, was born and her presence forever altered Julia’s position in the family although the change was not immediately apparent.
When the Selmes family returned to their ranch, Julia continued to cook and clean but now she was also asked to take care of the infant, Isabella. When the family removed to St. Paul and as Isabella grew older, she came more and more under the African American woman’s care and the family began to refer to Julia as “Mammy” – a reference to antebellum times. Neither Patty nor Julia Dinsmore had a “mammy” as a child. However, in the late 1800s, the term in reference to African American nannies reappeared among European Americans. Interestingly, Julia Loving only referred to herself as “Mammy” when she was writing to Isabella; when she wrote to Julia Dinsmore, she more often than not used her given name. Although she may have considered “Mammy” to be like a nickname—Isabella was “Dimp,” Patty was “Muddy,” and Julia Dinsmore was “Owny”—outside the family only an African American woman could be a “Mammy.”
Although Julia secretly contemplated marriage again in 1892, she never did leave the Selmes family and their descendants. Following Tilden Selmes’ death in 1895, Julia and Isabella moved in with Patty’s father in St. Paul, where Isabella was to begin her schooling. Since she was tutored at home, Julia had the opportunity to sit in on some of the lessons and her letters indicate that she did just that, becoming fluent in French and knowledgeable in contemporary fiction. She maintained a close relationship with the Flandrau family and with Julia Dinsmore in Kentucky. There is reason to believe that she may have even been acquainted with or employed by the Flandrau family prior to being hired to go to the Dakota Territory. Julia wrote to Patty in 1885 about the medical troubles her sister was having and concluded, “I guess I will have to get some money from your Father to send her home.” 2 The Flandrau and Dinsmore family also went out of their way to help Walter Loving. Patty had hired Walter in the mid 1880s, but finding him unreliable she sent him to school in St. Paul to learn to wait tables. Graduating from high school in Washington, D.C., he enlisted as a musician in the 24th Regiment of the Infantry. As the Dinsmore descendants recollected, Julia Dinsmore was so impressed with Walter’s musical abilities that she paid to send him to the New England Conservatory of Music in Boston, where he learned to conduct. He served as bandmaster in several units but wanted to go to the Philippines during the Spanish-American War. Both Patty Selmes and her father, Charles Flandrau, wrote to Vice-President, and then President, Theodore Roosevelt, and in 1902, Walter became the bandmaster of the Philippine Constabulary Band, which “won recognition for it superior performances” and toured widely. 3 Many years later he died in the Philippines.
In 1901, Julia Loving accompanied Isabella and Patty to New York City where Isabella was to attend school. When Patty decided to take Isabella to Europe, she insisted that Julia go along, and Julia decided that it would be best for her to do so, since Patty had begun drinking after her husband’s death. In writing to Julia Dinsmore to decline the latter’s invitation to spend the summer at Boone, Julia Loving described the necessity of her going with Isabella to Europe and concluded the letter with a somber note, “Think of me at my post, as the boy stood on the burning deck when all but him had fled.” 4 The lines recalled to both women the poem, “Casabianca” based on an event that occurred during the Battle of the Nile in 1798, when a young boy refused to leave a burning ship because his dead father would not give him permission. She kept an eye on Isabella when Patty could not, but she was also able to enjoy herself in England and France, touring Windsor Castle and the Tower of London, among other sites. From England, Julia wrote about the impression she made on other servants by her fluency in French and by Patty asking her for money in front of them, wondering aloud if the African American and white women were related. 5
A year after their return from Europe, Julia was helping Isabella through her debutante season. While Patty chaperoned and mended dresses, Julia accompanied Isabella to several overnight parties, including a stay at the White House. Martha Ferguson Breasted, Isabella’s daughter, retold the story later, emphasizing the fact that what most impressed Julia about her visit to our nation’s capital was that she was allowed to enter the White House through the front door. Since Julia had known the President from their days in the Dakota Territory together, this story may have some truth to it.
Julia’s relationship with the Selmes’ women deteriorated after Isabella married Robert Ferguson in 1905, perhaps as a result of Patty’s drinking or maybe as a result of Julia’s ambiguous position. With her charge married, she stayed with Sally Cutcheon in Long Island and waited for Isabella and Robert to need her. One year after their marriage, with the birth of Martha, Julia took up her former role and quickly became very attached to the little girl and her brother, Bobby, and she even agreed to move to the mountains of New Mexico to continue taking care of them. At fifty-three, Julia found herself living in a tent and doing all sort of odd jobs which she described to Julia Dinsmore in a letter, “I go from 630 until 930 P.M. only stopping to eat my meals. With two children, 28 chickens, washing, and ironing for the children, gathering wood, taking care of our tent is enough for one of my age.” 6 In 1913, she fell ill and went to New York City to undergo a hysterectomy, recuperating in Boone County with Julia Dinsmore.
For the remainder of her life, which was a long one, Julia Loving appears to have stayed in California. When Isabella bought property in Santa Barbara in 1920, Sally followed suit, so the families could spend time together. Sally had a place for Julia to stay so she kept an eye on both houses. Patty continued to send her a monthly allowance and after Patty died, Sally and Isabella did the same. Eventually, Julia moved to Los Angeles where her brother Walter occasionally lived and where Martha Ferguson visited her often. When Julia died in 1950, Isabella had her brought back to Boone County where she was buried in the same graveyard as Julia Dinsmore, Patty Selmes, and, later, Dimp – the women with whom she had spent so much of her adult life.
Unfortunately, the racism Julia must have dealt with during her life followed her almost literally to her grave. The undertaker who picked her coffin up at the airport, realizing that he was transporting a deceased African American, dropped her coffin at the end of the Dinsmore driveway and refused to move it, leaving it to the family to transport Julia’s six-foot frame up the steep hill to the graveyard. Forty-five years later, when Martha Ferguson Breasted died, she requested that her body be cremated and her ashes be placed in the grave of Julia Farley Loving. Julia remains the sole African American buried in the family graveyard who has an engraved headstone.
1 Julia Farley Loving to Patty F. Selmes, 11 November 1885. 2 Julia Farley Loving to Patty F. Selmes, 18 December 1885. 3 Albert E. Wier, ed., The Macmillan Encyclopedia of Music and Musicians in One Volume (New York: The Macmillan Company, 1938), n.p. 4 Julia Farley Loving to Julia Dinsmore, 10 May 1903. 5 Ibid., 15 July 1903. 6 Ibid., 30 December 1910.`, imageUrl: "http://www.dinsmorefarm.org/wp-content/uploads/2019/02/Julia_Farley_Loving.jpg" },
  { slug: "nancy-mcgruder", name: "Nancy McGruder", bio: `Nancy McGruder (1810-1906)
Nancy McGruder was born in 1810 in Kentucky. She was brought to the Dinsmore farm by James Dinsmore in 1842, after his father’s death. She was probably the daughter of a woman named Lucy, who was also brought to the farm at the same time. Nancy was literate, which was unusual for an enslaved person at that time. She was also a skilled seamstress and cook. She was often referred to as “Aunt Nancy” by the Dinsmore family, a term of endearment and respect. However, Nancy herself preferred to sign her letters “Nancy Mcgruder,” without the “Aunt.” This suggests that she was aware of her status as an enslaved person and did not want to be seen as a member of the Dinsmore family.
Nancy was married to an enslaved man named Noah, who lived on a neighboring farm. They had several children together. Noah died in 1851. In 1865, Nancy left the Dinsmore farm and moved to Oxford, Ohio, a town known for its abolitionist sentiments. She later returned to the Dinsmore farm and lived in a cabin on the property. In the early 1890s, her cabin burned down, and she moved into the kitchen cabin, where she lived until her death in 1906. Nancy was approximately ninety-six years old when she died.
1 John Minor to James Dinsmore, 17 May 1825, file 1994. 2 Middle Creek Baptist Church, microfilm, 24 February 1844 and October 1851. 3 Nancy Mcgruder to Julia Dinsmore, 6 September 1877. 4 Enid Yandell, “A Corner in Kentucky,” Filson Historical Society, MSS.A Y21b Folder 73. 5 Julia Dinsmore to Sally F. Cutcheon, 5 August, 1906. 6 Julia Dinsmore Journal, 30 July 1906`, imageUrl: "https://www.dinsmorefarm.org/wp-content/uploads/2019/07/Nancy-McGruder-200x300.jpg" },
];
